### ISSUE TITLE
Issues porting over

### ISSUE THREAD

**Issue by SheldonCurtiss** [JimOhman/model-based-rl#10]
![ubuntu_yWVVNVr8ng](https://user-images.githubusercontent.com/78921582/133953851-7305c52f-725e-47be-8d4a-0cd1dc761343.png)

Any idea what's causing this?

**Comment by JimOhman** [comment]
What arguments did you use for your run?

**Comment by SheldonCurtiss** [comment]
train.py --environment tictactoe --architecture MuZeroNetwork --batch_size 32 --log actors learner --num_actors 6  --td_steps 120 --discount 1 --stored_before_train 20000 --group_tag MainGroup --run_tag Run1

Modified tictactoe for it

**Comment by JimOhman** [comment]
I see, the problem is that the convolutional blocks in MuZeroNetwork (also TinyNetwork) is written for 96x96 inputs, while TicTacToe provides 9x9. These networks are also a bit heavy for TicTacToe, I'd suggest using FCNetwork instead.
