### ISSUE TITLE
Why model not training?

### ISSUE THREAD

**Issue by TheGravityZero** [JimOhman/model-based-rl#14]
I want to say thanks to author for this implementation!
When I started to train on Breakout-ramNoFrameskip-v4 a few hours later the model was able to achieve well result. Sum of reward was about 300-400. Maximum was about 800.
When I tried to train model on Breakout-NoFrameskip-v4, which uses image observation the model does want to learn.
Anyone could learn on Breakout-NoFrameskip-v4? What nets did you use?

**Comment by JimOhman** [comment]
I have not fully trained a model on the environments with pixel inputs, as I did not have the compute resources to experiment with this. But, I remember getting something like 200+ on Breakout after 24 hours of training using TinyNetwork. You might have to provide the --wrap_atari and --stack_actions for this to work as well, though, they might or might not be buggy at the moment. But keep in mind that these networks are quite large (even TinyNetwork), and the inputs are pixels, so expect a significantly longer time to train on the same hardware.
