### ISSUE TITLE
fix_temperatures incorrectly defined

### ISSUE THREAD

**Issue by TheGravityZero** [JimOhman/model-based-rl#15]
Hello,
When we set  --fixed_temperatures 1.0 0.8 0.7 0.5 0.3 0.2 0.1, each of 7 actors take temperature corresponding this list and each of actors play game with his temperature to end.
Also implemented visit_softmax_temperature, when fixed temperature undefined each of actors have the same temperature corresponding visit_softmax_temperature function.
But in code:
```
    if self.config.fixed_temperatures is not None:
        self.temperature = self.config.visit_softmax_temperature(self.training_step)
```
I thing, it means if fixed_temperatures is defined we use visit_softmax_temperature, but it is wrong.
Correct code:
```
    if self.config.fixed_temperatures is None:
        self.temperature = self.config.visit_softmax_temperature(self.training_step)
```
Сorrect me if i'm wrong, thanks!

**Comment by JimOhman** [comment]
I believe you're correct, fixed it, thanks!
