### ISSUE TITLE
--no_support and support_size variables

### ISSUE THREAD

**Issue by emmeburgin** [JimOhman/model-based-rl#5]
Unless I'm mistaken, it seems that if the user provides the ``--no_support`` option, the default support size range (-15 to 15) is still used in determining the values for ``value_support_size`` and ``reward_support_size``, which in turn show up as parameters in each of the networks. That seems strange. Is this intentional?

**Comment by JimOhman** [comment]
This is unintentional, thanks for noticing!

The option --no_support was added and experimented with the fully-connected network and the TinyNetwork, and the changes for MuZeroNetwork was simply forgotten. I added these now.

Thanks!
