### ISSUE TITLE
Extension to two-player games?

### ISSUE THREAD

**Issue by emmeburgin** [JimOhman/model-based-rl#6]
Thanks for responsiveness to previous issues.

There are a number of publicly available model-based RL implementations, but I've come to like this one. However, I'm interested in exploring training with self-play in a symmetrical two-player game. Are there plans to extend this package for that purpose? Do you have some idea of how difficult it would be? Depending on the level of commitment necessary I may be willing to contribute the code via pull request.

Thanks again!

**Comment by JimOhman** [comment]
Oh, sorry about the not so responsive response this time. I've been abroad and currently do not have my computer available.

My feeling of adding two-player support is that it shouldn't be too much effort if you are familiar with the code. I was planning on working on this when I get back, which is in a couple of weeks.

**Comment by JimOhman** [comment]
I've added support for two-player games now. To add your own game it has to be in the style of an OpenAI game, check my Tic-Tac-Toe implementation under the environments folder for an example if needed.
