### ISSUE TITLE
window_size must be great than stored_before_train

### ISSUE THREAD

**Issue by ipsec** [JimOhman/model-based-rl#7]
Hi Jim,

I think argparser allow you to check if window_size >= stored_before_train.

I set stored_before_train  to 1000 and learner never started because this line[1]:

while ray.get(self.replay_buffer.size.remote()) < self.config.stored_before_train:
    time.sleep(1)

[1] https://github.com/JimOhman/model-based-rl/blob/d521e7d2c0775c457886a1f35483f7bc04c5c954/learners.py#L87

**Comment by JimOhman** [comment]
I'll put that check in, thanks.
