### ISSUE TITLE
extension to continuous action space of LunarLanderContinuous-v2?

### ISSUE THREAD

**Issue by meioses** [JimOhman/model-based-rl#9]
I appreciate your excellent implementation of MuZero.

Is it possible to extend your MuZero code to continuous action space?
If I read your code correctly, it is for discrete actions only, e.g., for the four actions of 'do nothing','fire left engine','fire right engine', and 'fire downward main engine' for LunarLander-v2 environment.

Which part of the code should be changed to make it run with continuous action space, e.g., for https://gym.openai.com/envs/LunarLanderContinuous-v2 environment, to enable continuous control? Thank you.

**Comment by JimOhman** [comment]
Thanks!

Yeah, it is currently only for discrete actions. I've yet to extend it to continuous action spaces. However, it is possible following the approach from https://arxiv.org/pdf/2006.07430.pdf, and I think the changes are mostly for the MCTS code and action selection.

**Comment by ipsec** [comment]
More details [here](https://www.furidamu.org/blog/2021/07/18/sampled-muzero--learning-and-planning-in-complex-action-spaces/) and [here](https://drive.google.com/file/d/1cZqh7dxI4oUszPpio22oNjFRvt3Y_ohN/)
